conf.py:
  copyright: 2012-2017
  project: AJAX Social Network Components
  version: 9.2
  release: 9.2.9
  latex_documents:
  - - Index
    - restdoc.tex
    - AJAX Social Network Components
    - Gisele Wendl
    - manual
  latex_elements:
    papersize: a4paper
    pointsize: 10pt
    preamble: \usepackage{typo3}
  intersphinx_mapping:
    t3tsref:
    - http://docs.typo3.org/typo3cms/TyposcriptReference/
    - null
  extlinks:
    forge:
    - http://forge.typo3.org/issues/%s
    - 'Forget ticket #'
  extensions:
    - sphinx.ext.intersphinx
    - t3sphinx.ext.t3extras
    - t3sphinx.ext.t3tablerows
    - t3sphinx.ext.targets
    - sphinx.ext.extlinks
    - sphinxcontrib.youtube